### ISSUE TITLE
Why does SailsService look for io connection and immediately close it

### ISSUE THREAD

**Issue by mryarbles** [joeherold/angular2-sails#1]
When you include sails.io.js on page it automatically creates connection.  Then when you import angular2-sails it immediately disconnects that previous connection.  Why?  What is the best way to instantiate the two?

```
if (io && io.sails) {
    if (io && io.socket && io.socket.isConnected) {
        io.socket.disconnect();
    }
}
```

**Comment by joeherold** [comment]
its because of the connection options you may pass in the initiation.
[passing options: angular2-sails working with it](https://github.com/joeherold/angular2-sails#working-with-it)

think of using different or changing connections than the local url of your sails app or creating a ios/android app. best way is to disable autoconnect in sails.io.js by passing this parameter or changing it in the template:
`io.sails.autoConnect = false;`
